### ISSUE TITLE
[FEAT] Add option to revert to v4.6.0 Dark color scheme

### ISSUE THREAD

**Issue by Derpitron** [orblazer/discord-nordic#22]
I personally do not like the v4.8.0 color scheme, as I think it is too dark for me. An option to load the old color scheme would be much appreciated.

**Comment by orblazer** [comment]
Hello, i'm aware that change could be controversial.
If multiple users want revert i can re add the old theme to an "classic" version, so please up vote this issue for let me know.

**Comment by dboling19** [comment]
I thought the theme was following the NordTheme from Arctic Ice Studios.  If this is going through a color change, I will look into making my own theme then.

**Comment by DarkReaper231** [comment]
> I thought the theme was following the NordTheme from Arctic Ice Studios. If this is going through a color change, I will look into making my own theme then.

I think what he means is that there will be two, one that will follow it more closely and second "classic" version for people that like some level of color diversity between panels

**Comment by orblazer** [comment]
Hello,
For explain why i have changes is because elevate elements should be done with lighten colors and not darken and want unify the theme.

But i work on brighten variant by using `nord1` instead of `nord0` to be more confortable (for me at least) to read and also more match other softwares (with [Nord GTK theme]) and less only code softwares.

For that change i have make some rapid test and i'm open to ideas and suggestion. You can vote to one of this changes by reacting to message.
| Theme | Preview |
|----|---|
| :eyes: **Actual** | ![actual-dark](https://raw.githubusercontent.com/orblazer/discord-nordic/master/.github/preview.png) | 
| :+1: **New 1** | ![Screenshot_20230218_033516](https://user-images.githubusercontent.com/1344792/219827322-868d8b62-0b91-497c-9769-c7e7255018d0.png)  |
| :heart: **New 2** | ![Screenshot_20230218_030554](https://user-images.githubusercontent.com/1344792/219826657-75aee4fa-e812-4765-a1be-6503720a921e.png) |
| :tada: **New darken** | ![Screenshot_20230218_030753](https://user-images.githubusercontent.com/1344792/219826730-8e289870-67d0-4daa-b02b-5d266c5286e2.png) |

Thanks.

**Comment by Derpitron** [comment]
You are going above and beyond with these theme designs! I commend your effort, and hope that the other themes are accessible through some CSS variables or similar.

**Comment by DarkReaper231** [comment]
I enabled opacity on my Firefox window to make a comparassion

![image](https://user-images.githubusercontent.com/38611351/219864815-7d418b0a-e3b5-4e41-a426-0d55d3768364.png)
![image](https://user-images.githubusercontent.com/38611351/219864820-95fbc581-efc7-47d5-a188-ffe8e3ebbeee.png)
![image](https://user-images.githubusercontent.com/38611351/219864823-38add4dc-9d91-4411-9cb3-e44654e223a3.png)
![image](https://user-images.githubusercontent.com/38611351/219864826-532121e5-50fa-4960-bc82-1a43036c721c.png)

I don't know, I still prefer 4.7.0, I have no way to showcase it now because it's currently broken in newest version of Discord

**Comment by orblazer** [comment]
*Update: i have add  __New 3__ theme with a bit darken colors for match other apps background*

**Comment by DarkReaper231** [comment]
> _Update: i have add **New 3** theme with a bit darken colors for match other apps background_

**New 2** still looks best from these but 4.7.0 is still best

**Comment by orblazer** [comment]
Hello,
I couldn't wait for work on that :sweat_smile:, so this is what should like in next update :

| Normal | Uniform |
|:---:|:---:|
| ![preview](https://user-images.githubusercontent.com/1344792/219985308-c4f9a560-235c-465a-a38b-dc0cf5cfbaf4.png) | ![preview](https://user-images.githubusercontent.com/1344792/219985282-dceb702c-cde5-46ba-a35f-ce81fc683067.png) |

I'm not sure how to name the "uniform" variant.
Also if you have some returns to adjust that version, its the time, before i release next update.

*__NOTE__: the changes is pushed but the files is not built.*

**Comment by Derpitron** [comment]
Name the Uniform theme as **Classic**
Name the Normal theme as **Neo**

**Comment by DarkReaper231** [comment]
> Hello, I couldn't wait for work on that 😅, so this is what should like in next update :
> Normal 	Uniform
> ![preview](https://user-images.githubusercontent.com/1344792/219985308-c4f9a560-235c-465a-a38b-dc0cf5cfbaf4.png) 	![preview](https://user-images.githubusercontent.com/1344792/219985282-dceb702c-cde5-46ba-a35f-ce81fc683067.png)
> 
> I'm not sure how to name the "uniform" variant. Also if you have some returns to adjust that version, its the time, before i release next update.
> 
> _**NOTE**: the changes is pushed but the files is not built._ _**NOTE2**: I have also try with brighten reaction color ![Screenshot_20230220_021223](https://user-images.githubusercontent.com/1344792/219987935-c38ad1d4-3c67-4e9f-993d-c45102dcd6bf.png)_

Could you please add a config or something to change the brightness of all colors? Like if I want to make the colors just a tiny bit darker so it fits more on my display? It would be nice touch to allows some sort of manual adjustment without having to go to color picker and overwrite all colors manually.

**Comment by Derpitron** [comment]
> Could you please add a config or something to change the brightness or saturation of all colors? Like if I want to make the colors just a tiny bit darker so it fits more on my display? It would be nice touch to allows some sort of manual adjustment without having to go to color picker and overwrite all colors manually. Perhaps add this option for like 3 main colors? Like in the screenshot we see left panel, the middle section and the right panel. And that this setting would allow to adjust these three colors for entire Discord.
> 
> Like `--primary` `--secondary` `--tertiary` And like add that to the **CUSTOMIZATION** part of the css file
> 
> This would satisfy everyone because if the colors aren't quite there for someone, they could tune them up or down

Regrettably, CSS styles simply do not support this kind of "hot swapping" of variables which would be used in the average programming language. This is not possible to do AFAIK

**Comment by orblazer** [comment]
Hello,
This is done with v4.9.0 with commit 0219d603b6fd31dcf10d13d68b8bf62be3310d18.

**Comment by Derpitron** [comment]
![image](https://user-images.githubusercontent.com/46134462/221092289-c58d19cf-098c-4dfc-b641-42ed76672275.png)
The contrast between the text in the chat area and the background seems too small to be comfortable.

**Comment by orblazer** [comment]
Hello @Derpitron, i have tweak text colors in v4.9.1 for have AAA accessibility in text and at least AA on other (channel name and message time)
