### ISSUE TITLE
[FEAT] Re-release the darker version (4.8) of this theme as a seperate theme.

### ISSUE THREAD

**Issue by BurntKrispe** [orblazer/discord-nordic#25]
I preferred the 4.8 darker version over the older/latest. Creating a branch of the theme and making it available through Better Discord's repositories will make it available to those who prefer it without shocking some users when an update changes it's appearance.

**Comment by orblazer** [comment]
Hello @Burntninjas,
You could download uniform variant here https://github.com/orblazer/discord-nordic/tree/master/uniform. And its planned to move it in other branch for published separate versions on better discord.

**Comment by orblazer** [comment]
Hello,
Due to refused submit for "uniform" theme, i have only 3 possibility :
1. :tada: keep file in different folder/branch **BUT** we can't auto update
2.  :rocket: use static import  (so simply uncomment lime) so we have update notification **BUT** we need re toggle comment on every update
3. :heart: use dynamic import (so simply uncomment lime) we doesn't need re toggle comment after every update, we have auto update **BUT** the version in discord its not update and we doesn't have update notification

So, i wait some times for see what is the best option to manage it.
